Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [139]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(f"Matrix\n {a}")

Matrix
 [ 1  2  3  4  5  6  7  8  9 10]


Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [15]:
import random
m = np.zeros((3, 3), dtype=int)
for i in range(3):
    m[i] = 0
print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [141]:
b = np.zeros((5, 5), dtype=int)
for i in range(5):
    b[i] = random.choices(range(1, 11), k=5)
print(b)

[[ 8  5  7  6  6]
 [ 8  4  3  3  4]
 [ 6  5 10  2  5]
 [ 1  6  2  5  4]
 [ 2  4  4  4 10]]


Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [19]:
k = np.random.rand(4, 4)
print(k)

[[0.29596598 0.00422933 0.87618643 0.02465551]
 [0.41051331 0.072606   0.40122913 0.34819559]
 [0.03635795 0.21855029 0.54506431 0.65194714]
 [0.96539862 0.88611063 0.86986711 0.42248594]]


Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [41]:
a = np.zeros(5, dtype=int)
for i in range(5):
    a[i] = random.choice(range(1, 11))
    
b = np.zeros(5, dtype=int)
for k in range(5):
    b[k] = random.choice(range(1, 11))

print(a)
print(b)

print(f"Sum of two one-dimentional vectors --> {a+b}")
print(f"Difference of two  one-dimentional vectors --> {a-b}")
print(f"Multiplication of two one-dimentional vectors --> {a*b}")

[5 1 9 9 4]
[2 9 8 3 8]
Sum of two one-dimentional vectors --> [ 7 10 17 12 12]
Difference of two  one-dimentional vectors --> [ 3 -8  1  6 -4]
Multiplication of two one-dimentional vectors --> [10  9 72 27 32]


Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [43]:
a = np.zeros(7, dtype=int)
for i in range(5):
    a[i] = random.choice(range(1, 100))
    
b = np.zeros(7, dtype=int)
for k in range(5):
    b[k] = random.choice(range(1, 100))

print(a)
print(b)

result = np.dot(a, b) #dot - скалярний добуток
print(f"scalar product of vectors --> {result}")


[70 27 11 44 83  0  0]
[65 77 98 28 54  0  0]
scalar product of vectors --> 13421


Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [53]:
a = np.zeros((2, 2), dtype=int)
for i in range(2):
    a[i] = random.choices(range(1, 10), k=2)
    
b = np.zeros((2, 3), dtype=int)
for k in range(2):
    b[k] = random.choices(range(1, 10), k=3)

print(a)
print(b)

result = np.dot(a, b) #або @ для перемноження 2 матриць
print(f"Multiplication of two matrices --> {result}")

[[6 8]
 [5 3]]
[[3 8 4]
 [7 3 3]]
Multiplication of two matrices --> [[74 72 48]
 [36 49 29]]


Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [62]:
a = np.zeros((3, 3), dtype=int)
for i in range(3):
    a[i] = random.choices(range(1, 10), k=3)

print(f"Usual matrix --> \n{a}\n")

a_inv = np.linalg.inv(a) #inv - для оберненої матриці
print(f"wrapped function --> \n{a_inv}")

Usual matrix --> 
[[4 1 1]
 [2 1 6]
 [9 3 4]]

wrapped function --> 
[[ 1.07692308  0.07692308 -0.38461538]
 [-3.53846154 -0.53846154  1.69230769]
 [ 0.23076923  0.23076923 -0.15384615]]


Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [63]:
a = np.random.rand(4, 4)
b = a.T # T - транспонована матриця
print(f"Usual matrix --> \n{a}\n")
print(f"Transposed matrix --> \n{b}")

Usual matrix --> 
[[0.99473895 0.48731572 0.33556189 0.48939543]
 [0.23927032 0.86725365 0.29799381 0.82425107]
 [0.31427401 0.04514233 0.738764   0.56957299]
 [0.61329774 0.12863743 0.03729759 0.60695737]]

Transposed matrix --> 
[[0.99473895 0.23927032 0.31427401 0.61329774]
 [0.48731572 0.86725365 0.04514233 0.12863743]
 [0.33556189 0.29799381 0.738764   0.03729759]
 [0.48939543 0.82425107 0.56957299 0.60695737]]


Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [142]:
a = np.zeros((3, 4), dtype=int)
for i in range(3):
    a[i] = random.choices(range(1, 10), k=4)
    
b = np.zeros(4, dtype=int)
for i in range(4):
    b[i] = random.choice(range(1, 11))
print(f"Matrix --> \n{a}\n")
print(f"Vector --> \n{b}\n")

print(f"Multiplication -->\n{np.dot(a, b)}")

Matrix --> 
[[2 4 1 6]
 [1 6 6 5]
 [7 3 1 4]]

Vector --> 
[7 9 4 1]

Multiplication -->
[60 90 84]


Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [93]:
a = np.random.rand(2, 3)
b = np.random.rand(3)

print(f"Matrix --> \n{a}\n")
print(f"Vector --> \n{b}\n")
result = np.dot(a, b)

print(f"Multiplication -->\n{result}")


Matrix --> 
[[0.89336384 0.13909965 0.31367399]
 [0.05719893 0.94813584 0.70064198]]

Vector --> 
[0.817248   0.88190645 0.02090699]

Multiplication -->
[0.85933068 0.89756115]


Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [81]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))


print(f"Matrix 1 --> \n{a}\n")
print(f"Matrix 2--> \n{b}\n")

result = np.multiply(a, b) #або можна використати звийчайни знак множення *
print(f"Element-wise multiplication of two matrices --> \n{result}")

Matrix 1 --> 
[[ 2 10]
 [ 5  4]]

Matrix 2--> 
[[8 1]
 [4 2]]

Element-wise multiplication of two matrices --> 
[[16 10]
 [20  8]]


Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [84]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
print(f"Matrix 1 --> \n{a}\n")
print(f"Matrix 2--> \n{b}\n")
result = np.dot(a, b)
print(f"Matrix product of a and b --> \n{result}")

Matrix 1 --> 
[[5 3]
 [1 5]]

Matrix 2--> 
[[9 1]
 [6 1]]

Matrix product of a and b --> 
[[63  8]
 [39  6]]


Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [100]:
a = np.random.randint(1, 101, size=(5, 5))
print(a)
result = np.sum(a)
print(f"\nSummary --> {result}")

[[37 52 24 87 37]
 [71 69 20  1  2]
 [49 33 43 15 71]
 [10 99 74 69 87]
 [39 83 96 86 96]]

Summary --> 1350


Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [105]:
a = np.random.randint(1, 101, size=(4, 4))
b = np.random.randint(1, 101, size=(4, 4))

print(f"Matrix 1\n {a}")
print(f"Matrix 2\n {b}")

result = a - b
print(f"\nDifference --> \n{result}")

Matrix 1
 [[94  2 98 88]
 [53 37 91 73]
 [38 76 81 26]
 [65 36 27  7]]
Matrix 2
 [[78 21 56 55]
 [ 1 42 20 71]
 [94 25 19 59]
 [ 3 45 75 11]]

Difference --> 
[[ 16 -19  42  33]
 [ 52  -5  71   2]
 [-56  51  62 -33]
 [ 62  -9 -48  -4]]


Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [119]:
a = np.random.rand(3, 3)
print(f"Matrix \n {a}\n")
row_sums = np.sum(a, axis=1)
column_vector = row_sums.reshape(-1, 1)
print(f"Vector -->\n{column_vector}")

Matrix 
 [[0.97938362 0.43904186 0.65478495]
 [0.76297957 0.30943057 0.33303753]
 [0.1795751  0.64533766 0.16124897]]

Vector -->
[[2.07321043]
 [1.40544768]
 [0.98616173]]


Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [143]:
a = np.random.randint(1, 10, size=(3, 4))
print(f"Matrix\n {a}")

result = np.square(a)
print(f"\nSquare --> \n{result}")

Matrix
 [[1 3 3 6]
 [5 5 3 2]
 [6 6 8 3]]

Square --> 
[[ 1  9  9 36]
 [25 25  9  4]
 [36 36 64  9]]


Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [138]:
a = np.zeros(4, dtype=int)
for i in range(4):
    a[i] = random.choice(range(1, 50))
print(f"Matrix\n {a}")

    
result = np.sqrt(a)

print(f"\nSqrt --> \n{result}")

Matrix
 [49 46 26 39]

Sqrt --> 
[7.         6.78232998 5.09901951 6.244998  ]
